name: PR Author Issue Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr-author-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR Author
        id: get-author
        run: echo "pr_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Get Linked Issues
        id: get-issues
        run: |
          issues=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=${{ github.event.pull_request.number }}")
          echo "issues=$(echo $issues | jq -c '.[]')" >> $GITHUB_ENV

      - name: Check PR Author Assignment
        run: |
          issues=$(echo "${{ env.issues }}" | jq -r '. | @base64')
          for issue in $issues; do
            _jq() {
              echo $issue | base64 --decode | jq -r ${1}
            }
            assignees=$(_jq '.assignees | map(.login)')
            if [[ ! " ${assignees[@]} " =~ " ${{ env.pr_author }} " ]]; then
              echo "PR author is not assigned to issue $(_jq '.number')"
              exit 1
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
